name: Announce release to db

on:
  release:
    types: [published]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Announcement API
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://prickle-silky-cerise.glitch.me/api/add-announcement
          method: POST
          headers: ${{ toJSON({ "Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.ANNOUNCE_TOKEN }}" }) }}
          payload: ${{ toJSON({ "title": github.event.release.name, "message": github.event.release.body }) }}
