name: Announce release to db

on:
  release:
    types: [published]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Announcement API
        run: |
          curl -X POST https://prickle-silky-cerise.glitch.me/api/add-announcement \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.ANNOUNCE_TOKEN }}" \
            -d '{
              "title": "${{ github.event.release.name }}",
              "message": "${{ github.event.release.body }}"
            }'
