name: Announce to web app

on:
  release:
    types: [published]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://prickle-silky-cerise.glitch.me/api/announcement'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: |
            {
              "title": "${{ github.event.release.name }}",
              "message": "${{ github.event.release.body }}"
            }
