name: Announce release to database

on:
  release:
    types: [published]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Announcement API
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://prickle-silky-cerise.glitch.me/api/add-announcement
          method: POST
          payload: |
            {
              "title": "${{ github.event.release.name }}",
              "message": "${{ github.event.release.body }}"
            }
          headers: |
            {
              "Content-Type": "application/json"
              "Authorization": "Bearer ${{ secrets.ANNOUNCE_TOKEN }}"
            }
