name: Announce to database

on:
  release:
    types: [published]

jobs:
  announce:
    runs-on: ubuntu-latest

    steps:
      - name: Send Release Announcement to API
        id: api-request
        uses: muhfaris/request-action@v1
        with:
          url: https://prickle-silky-cerise.glitch.me/api/add-announcement
          method: POST
          headers: |
            {
              "Content-Type": "application/json",
              "Authorization": "Bearer ${{ secrets.ANNOUNCE_TOKEN }}"
            }
          body: |
            {
              "title": "${{ github.event.release.name }}",
              "message": "${{ github.event.release.body }}"
            }
